**FUNCTIONS**

In [1]:
def price_per_bedroom(price, bedrooms):
  return price / bedrooms

print(price_per_bedroom(250000, 3))
print(price_per_bedroom(180000, 2))

83333.33333333333
90000.0

In [4]:
def size_label(bedrooms):
  if bedrooms >= 4:
    return "big"
  else:
    return "small"

print(size_label(5))
print(size_label(2))

big
small

In [10]:
def is_expensive(price):
  if price > 200000:
    return True
  else:
    return False

print(is_expensive(345876543))
print(is_expensive(3445))

True
False

**UPLOADING OF DATA**

In [11]:
import pandas as pd

df = pd.read_csv("train.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [17]:
cols = ["SalePrice", "GrLivArea", "OverallQual", "YearBuilt", "Neighborhood", "BedroomAbvGr"]
small = df[cols]
small.head()

   SalePrice  GrLivArea  OverallQual  YearBuilt Neighborhood  BedroomAbvGr
0     208500       1710            7       2003      CollgCr             3
1     181500       1262            6       1976      Veenker             3
2     223500       1786            7       2001      CollgCr             3
3     140000       1717            7       1915      Crawfor             3
4     250000       2198            8       2000      NoRidge             4

In [18]:
small = df[cols].copy()

small["Size"] = small["BedroomAbvGr"].apply(size_label)
small.head()

,SalePrice,GrLivArea,OverallQual,YearBuilt,Neighborhood,BedroomAbvGr,Size
0,208500,1710,7,2003,CollgCr,3,small
1,181500,1262,6,1976,Veenker,3,small
2,223500,1786,7,2001,CollgCr,3,small
3,140000,1717,7,1915,Crawfor,3,small
4,250000,2198,8,2000,NoRidge,4,big

In [20]:
small["Size"].value_counts()

Size
small    1218
big       242
Name: count, dtype: int64