**LOAD THE HOUSING DATA INTO SQLITE**

In [7]:
import sqlite3
import pandas as pd

df = pd.read_csv("train.csv")

conn = sqlite3.connect("housing.db")
df.to_sql("houses", conn, if_exists="replace", index=False)

1460

In [8]:
pd.read_sql("SELECT COUNT(*) AS number_of_houses FROM houses", conn)

   number_of_houses
0              1460

**LOOKING AT 5 HOUSES**

In [10]:
# Looking at 5 houses
pd.read_sql("SELECT Neighborhood, SalePrice, GrLivArea FROM houses LIMIT 5", conn)

  Neighborhood  SalePrice  GrLivArea
0      CollgCr     208500       1710
1      Veenker     181500       1262
2      CollgCr     223500       1786
3      Crawfor     140000       1717
4      NoRidge     250000       2198

**THE 5 MOST EXPENSIVE HOUSES**

In [11]:
pd.read_sql("SELECT Neighborhood, SalePrice, GrLivArea FROM houses ORDER BY SalePrice DESC LIMIT 5", conn)

  Neighborhood  SalePrice  GrLivArea
0      NoRidge     755000       4316
1      NoRidge     745000       4476
2      NoRidge     625000       3627
3      NridgHt     611657       2364
4      NridgHt     582933       2822

**FILTERING IN SQL**

In [12]:
pd.read_sql("SELECT Neighborhood, SalePrice, GrLivArea FROM houses WHERE SalePrice > 400000 AND BedroomAbvGr >= 4",conn)

   Neighborhood  SalePrice  GrLivArea
0       OldTown     475000       3608
1       NoRidge     403000       2794
2       NridgHt     437154       2728
3       NoRidge     430000       3228
4       NoRidge     402000       2448
5       NoRidge     755000       4316
6       StoneBr     538000       3279
7       NridgHt     485000       3140
8       NridgHt     582933       2822
9       StoneBr     556581       2868
10      CollgCr     424870       2828
11      NoRidge     625000       3627
12      NoRidge     745000       4476
13      NoRidge     410000       3238

**USING GROUPBY**

In [13]:
pd.read_sql("""
SELECT Neighborhood, COUNT(*) AS houses
FROM houses
WHERE SalePrice > 400000 AND BedroomAbvGr >= 4
GROUP BY Neighborhood
ORDER BY houses DESC
""", conn)

  Neighborhood  houses
0      NoRidge       7
1      NridgHt       3
2      StoneBr       2
3      OldTown       1
4      CollgCr       1